version: "3"

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-node"
    restart: always
    volumes:
      - ./banco-de-dados-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234

volumes:
  banco-de-dados-api: